name: dirty-values
version: "0.2.0"
description: Checks for unused keys in a Helm chart's values files
ignoreFlags: false
platformCommand:
  - os: linux
    command: python3 ${HELM_PLUGIN_DIR}/main.py
platformHooks:
  install:
    - os: linux
      command: bash ${HELM_PLUGIN_DIR}/scripts/install.sh
